server:
  port: 8090
  address: 0.0.0.0
spring:
  datasource:
    username: root
    password: Xjw2039225151
    url: jdbc:mysql://localhost:3306/fraud?characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.example.fraud.sys.mapper: debug
